### ISSUE TITLE
Newline after typing single character

### ISSUE THREAD

**Issue by kirides** [VFPX/FoxcodePlus#1]
Hello, for some reason typing any character the cursor is set to the beginning of the next line leading to the follow-up characters being written on later lines instead after each other

e.g.
```
LOCAL loItem

*Typing loItem, see how the word is split into the beginning of each new line
l
oFUNC SomeFunc()
i
temENDFUNC
```
This does not happen when the new word is on the last line of a file

e.g.
```
LOCAL loItem
*Typing loItem
loItem
<<EOF>>
```

These are the settings i used
![vfp9_2019-01-30_12-57-11](https://user-images.githubusercontent.com/13602143/51979990-f3750800-248e-11e9-81d4-ac4264f80e0b.png)

**Comment by Ajitweb** [comment]
Hllo @kirides . I am facing the same issue. How did you solve it ?
